mode: development
media_root: media
media_url: /media
base_url: /
plugins:
  - hyde.ext.plugins.meta.MetaPlugin
  - hyde.ext.plugins.vcs.GitDatesPlugin
  - extensions.combine.CombinePlugin
  - hyde.ext.plugins.languages.LanguagePlugin
  - hyde.ext.plugins.meta.AutoExtendPlugin
  - hyde.ext.plugins.meta.SorterPlugin
  - hyde.ext.plugins.meta.TaggerPlugin
  - hyde.ext.plugins.css.LessCSSPlugin
  - extensions.css.CSSPrefixerPlugin
  - extensions.text.TextlinksPlugin
  - hyde.ext.plugins.text.TextlinksPlugin
  - extensions.images.ImageThumbnailsPlugin
  #- extensions.md2html.Md2HtmlPlugin
  
context:
  data:
    base: https://blog.gobyoung.com
    languages:
      cn: 简体中文
meta:
  nodemeta: meta.yaml
  author: Tanglim LUA
  title: "gobyoung"
  created: git
  modified: git
  language: cn
  disqus: cc98
  keywords: "gis, python, performance, netease"
  charset: utf-8
less:
  app: lessc
markdown:
  extensions:
    - codehilite
    - extra
    - toc
    - mathjax
  output_format: html
sorter:
  name:
    attr:
      - relative_path
  time:
    attr:
      - meta.created
    reverse: true
    filters:
      source.kind: html
      meta.listable: true
  time_cn:
    attr:
      - meta.created
    reverse: true
    filters:
      source.kind: html
      meta.listable: true
      meta.language: cn
tagger:
  sorter: time
  tags:
    "tutorial":
      descr: "邯郸学步"
    "tech":
      descr: "夜航船"
    "misc":
      descr: "酉阳杂俎"
    "myself":
      descr: "空山梵呗"
    "work":
      descr: "涉世之初"
publisher:
    github:
        type: hyde.ext.publishers.dvcs.Git
        path: ../goby.github.io
        url: github.com/goby/goby.github.io
