extends: base.j2
default_block: article

menu:
  -
     name: "The One"
     page: "http://gobyoung.com"
  -
     name: "Blog"
     type: "tags"
     page: "index.html"
  -
     name: "Projects"
     page: "https://github.com/goby"
  -
     name: "About"
     page: "about.html"
  -
     name: "Resources"
     page: "resources.html"
     