extends: base.j2
default_block: article

menu:
  -
     name: "The One"
     page: "http://gobyoung.com"
  -
     name: "Blog"
     page: "index.html"
  -
     name: "Projects"
     page: "#"
  -
     name: "About"
     page: "about.html"
     