extends: base.j2
default_block: article

language: cn
menu:
  -
     name: "Projects"
     page: "projects.html"
  -
     name: "Blog"
     page: "blog/"
l10n:
  otherlinks: "其他"
  translations: "其他可用语言"
  comments: "雁过留痕(Disqus)"
  attachments: "附件"
  tags: "分类"
  share: "分享TA"
