extends: base.j2
default_block: article

language: cn
menu:
  -
     name: "The One"
     page: "http://gobyoung.com"
  -
     name: "Blog"
     type: "tags"
     page: "index.html"
  -
     name: "Projects"
     page: "https://github.com/goby"
  -
     name: "About"
     page: "about.html"
     
l10n:
  otherlinks: "其他"
  translations: "其他可用语言"
  comments: "雁过留痕(Disqus)"
  attachments: "附件"
  tags: "分类"
  share: "分享TA"
  
listable: true
comments: true
class: article